config/routes.rb
Rails.application.routes.draw do

  # USERS MANAGEMENT
  devise_for :users
  post '/users', to: 'users#create'
  get '/users/expired', to: 'users#list_expired'

  resources :users

  # FILTERS
  resources :filters
  # TELESCOPES
  resources :telescopes
  # EYEPIECES
  resources :eyepieces
  # BINOCULARS
  resources :binoculars
  # CELESTIAL BODIES
  resources :celestial_bodies
  # OBSERVATIVE SESSIONS
  resources :observative_sessions do
  # OBSERVATIONS
  resources :observations
  end
  get '/report', to: 'observative_sessions#report'
  
  # OUTINGS
  resources :outings
  root to: 'application#index'
  
end

app/models/observation.rb
# == Schema Information
#
# Table name: observations
#
#  id                     :integer          not null, primary key
#  start_time             :datetime
#  telescope_name         :integer
#  binocular_name         :integer
#  eyepiece_name          :integer
#  filter_name			  :integer
#  rating                 :integer
#  description            :string
#  image                  :integer
#  notes                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :integer          not null
#  celestial_body_name    :integer
#  observative_session_id :integer          not null
#

#
# Classe modello per la tabella "observations".
#
class Observation < ApplicationRecord
  validates :celestial_body_name, presence: true
  
  # relazioni 
  belongs_to :observative_session
  belongs_to :user

end

app/controllers/observations_controller.rb
#
# Classe controller che implementa le funzionalità CRUD per la classe model "Observation".
#
class ObservationsController < ApplicationController
  before_action :set_observation, only: [:show, :edit, :update, :destroy]

  # Metodo che recupera i telescopi (eventualmente mediante ricerca), 
  # li ordina, attua una paginazione degli stessi ed in seguito
  # li visualizza.
  def index
  #@s = Observation.ransack(:observative_session)
  #@observations = @s.result.order(params[:order]).paginate(page: params[:page]) if params[:s].present?
  #@observations = @s.result.order(params[:order]).paginate(page: params[:page]) unless params[:s].present?
  #@observation = Observation.new
  end

  # Metodo ereditato dalla classe ApplicationController.
  def show
  end

  # GET /observations/new
  def new
	@observative_session = ObservativeSession.find(params[:observative_session_id])
    @observation = Observation.new(observative_session: @observative_session)
	@observation.user_id = @observative_session.user_id
  end

  # Metodo ereditato dalla classe ApplicationController.
  def edit
	@observative_session = ObservativeSession.find(params[:observative_session_id])
	@observation = @observative_session.observations.find(params[:id])
  end

  # Questo metodo crea un'istanza di Observation e la salva nel database.
  # Se l'operazione si conclude con successo, avverrà una redirezione alla pagina
  # che presenta i dettagli dello strumento creato. In caso contrario, verrà
  # visualizzato un messaggio d'errore.
  def create
    @observative_session = ObservativeSession.find(params[:observative_session_id])
    @observation = @observative_session.observations.build(observation_params)
	@observation.user_id = current_user.id
	
    respond_to do |format|
      if @observation.save
        format.html { redirect_to [@observative_session, @observation], notice: 'Observation was successfully created.' }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che aggiorna un'istanza di Observation. Se l'operazione avviene con successo,
  # avverrà una redirezione alla pagina che visualizza i dettagli dello strumento aggiornato.
  # In caso contrario, verrà visualizzato un messaggio d'errore.
  def update
	@observative_session = ObservativeSession.find(params[:observative_session_id])
    respond_to do |format|
      if @observation.update(observation_params)
        format.html { redirect_to [@observative_session, @observation], notice: 'Observation was successfully updated.' }
        format.json { render :show, status: :ok, location: @observation }
      else
        format.html { render :edit }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che elimina un'istanza di Observation. Se l'operazione avviene con
  # successo, il browser verrà redirezionato alla lista di telescopi.
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observative_session_url(@observation.observative_session_id), notice: 'Observation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_observation
      @observation = Observation.find(params[:id])
    end

    # Metodo che imposta i parametri richiesti e ammessi durante la creazione o la modifica
    # di un'istanza di Observation.
    def observation_params
      params.require(:observation).permit(:start_time, :celestial_body_name, :telescope_name, :binocular_name, :filter_name, :eyepiece_name, :rating, :description, :notes)
    end
end

app/helpers/observations_helper.rb
module ObservationsHelper


end

app/views/observations/_form.html.erb
<%= bootstrap_form_for ([@observative_session, @observation]) do |f| %>
  <div class="col-sm-3 clear">
  <%= f.time_field :start_time, label: 'Ora di inizio' %>
   </div>
   <div class="col-sm-9">
  <%= f.text_field :celestial_body_name, label: 'Corpo celeste' %> 
  </div>
  <div class="col-sm-6">
  <%= f.text_field :binocular_name, label: 'Nome binocolo:' %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :telescope_name, label: 'Nome telescopio:' %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :eyepiece_name, label: 'Oculare:' %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :filter_name, label: 'Filtro:' %>
  </div>
  <div class="col-sm-2">
  <%= f.number_field :rating, label: 'Rating', in: 0...11 %>
  </div>
  <div class="clear">
  <%= f.text_area :description, label: 'Descrizione' %>
  </div>
  <%= f.text_area :notes, label: 'Note:' %>
  <%= f.submit 'Aggiorna' %>
<% end %>

app/views/observations/_index.html.erb
<%= render 'observations/new_modal' %>
<div class="panel panel-default">
  <div class="panel-heading">
	<h1 class="panel-title">Gestione Osservazioni</h1>
  </div>
  <div class="panel-body">
    <p>Lista osservazioni</p>
	<p>
      Azioni disponibili:
      <span>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new-observation-modal">Inserisci nuova osservazione</button>
      </span>
    </p>
    <hr>
	<%= search_form_for @s, url: observative_session_path(params[:id]) do |f| %>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group">
            <label for="order">Ordina risultati per</label>
            <%= select_tag 'order', options_for_select([['Nessuno','Created_at DESC'], ['Ora', 'start_time'], ['Rating', 'rating']], params[:order] || ''), class: 'form-control', onchange: "$('#observation_search').submit();" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
		<th>Ora inizio</th>
        <th>Corpo celeste</th>
        <th>Telescopio</th>
		<th>Binocolo</th>
		<th>Osservatore</th>
        <th colspan="3">Azioni</th>
      </tr>
    </thead>

    <tbody>
      <% @observations.each do |observation| %>
        <tr>
		<td>
		<% if observation.start_time != nil %>
		  <%= observation.start_time.strftime("%H:%M") %>
		<% end %>
		</td>
		  <td><%= observation.celestial_body_name %></td>
          <td><%= observation.telescope_name %></td>
		  <td><%= observation.binocular_name %></td>
		  <td><%= observation.user.name %></td>
          <td><%= link_to 'Visualizza', observative_session_observation_path(@observative_session, observation) %></td>
		  <% if current_user == 'admin' || Date.today < current_user.subscription_expiration+31.days %>
			<td><%= link_to 'Modifica', edit_observative_session_observation_path(@observative_session, observation) %></td> 
            <td><%= link_to 'Elimina', observative_session_observation_path(@observative_session, observation), method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
		  <% end %>
		</tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/observations/_new_modal.erb
<div class="modal fade" id="new-observation-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Inserimento nuova osservazione</h4>
      </div>
      <div class="modal-body">
        <p>Inserire le informazioni richieste per la nuova osservazione:</p>
        <%= render 'observations/form' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/observations/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Modifica osservazione</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', observation: ([@observative_session, @observation]) %>
  </div>
</div>
<%= render 'layouts/footer_logged'%>

app/views/observations/index.html.erb
<%= render 'observations/new_modal' %>
<div class="panel panel-default">
  <div class="panel-heading">
	<h1 class="panel-title">Gestione Osservazioni</h1>
  </div>
  <div class="panel-body">
    <p>Lista osservazioni</p>
	<p>
      Azioni disponibili:
      <span>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new-observation-modal">Inserisci nuova osservazione</button>
      </span>
    </p>
    <hr>
	<%= search_form_for @s, url: observative_session_observation_path(params[:id]) do |f| %>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group">
            <label for="order">Ordina risultati per</label>
            <%= select_tag 'order', options_for_select([['Nessuno',''], ['Ora', 'start_time'], ['Rating', 'rating']], params[:order] || ''), class: 'form-control', onchange: "$('#observation_search').submit();" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
		<th>Ora inizio</th>
        <th>Corpo celeste</th>
        <th>Telescopio</th>
		<th>Binocolo</th>
		<th>Osservatore</th>
        <th colspan="3">Azioni</th>
      </tr>
    </thead>

    <tbody>
      <% @observations.each do |observation| %>
        <tr>
		<% if observation.start_time != nil %>
		  <td><%= observation.start_time.strftime("%H:%M") %></td>
		<% end %>
		  <td><%= observation.celestial_body_name %></td>
          <td><%= observation.telescope_name %></td>
		  <td><%= observation.binocular_name %></td>
		  <td><%= observation.user_name %></td>
          <td><%= link_to 'Visualizza', observation %></td>
		  <% if current_user == 'admin' || Date.today < current_user.subscription_expiration+31.days %>
			<td><%= link_to 'Modifica', edit_observative_session_observation_path(@observative_session, observation) %></td>
            <td><%= link_to 'Elimina', observation, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
		  <% end %>
		</tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/observations/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Creazione nuova osservazione</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', observation: ([@observative_session, @observation]) %>
  </div>
</div>
<%= render 'layouts/footer_logged'%>

app/views/observations/show.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">Informazioni osservazione</div>
      <div class="panel-body">
	    <p><strong>Osservatore:</strong> <%= @observation.user.name %></p>
        <p><span><strong>Ora inizio:</strong></span> 
		<% if @observation.start_time != nil %>
		<%= @observation.start_time.strftime("%H:%M") %>
		<% end %>
		</p>
		<p><span><strong>Corpo celeste:</strong></span> <%= @observation.celestial_body_name %></p>
        <p><span><strong>Binocolo:</strong></span> <%= @observation.binocular_name %></p>
		<p><span><strong>Telescopio:</strong></span> <%= @observation.telescope_name %></p>
        <p><span><strong>Oculare:</strong></span> <%= @observation.eyepiece_name %></p>
        <p><span><strong>Filtro:</strong></span> <%= @observation.filter_name %></p>
		<p><span><strong>Rating:</strong></span> <%= @observation.rating %></p>
		<p><span><strong>Descrizione:</strong> </span><%= @observation.description %></p> 
		<p><span><strong>Note:</strong></span> <%= @observation.notes %></p>
		<% if current_user == 'admin' || Date.today < current_user.subscription_expiration+31.days %>
        <%= link_to 'Modifica', edit_observative_session_observation_url(@observation.observative_session_id, @observation) %> |
        <% end %>
		<%= link_to 'Indietro', observative_session_url(@observation.observative_session_id) %>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer_logged'%>