config/routes.rb
Rails.application.routes.draw do

  # USERS MANAGEMENT
  devise_for :users
  post '/users', to: 'users#create'
  get '/users/expired', to: 'users#list_expired'

  resources :users

  # FILTERS
  resources :filters
  # TELESCOPES
  resources :telescopes
  # EYEPIECES
  resources :eyepieces
  # BINOCULARS
  resources :binoculars
  # CELESTIAL BODIES
  resources :celestial_bodies
  # OBSERVATIVE SESSIONS
  resources :observative_sessions do
  # OBSERVATIONS
  resources :observations
  end
  get '/report', to: 'observative_sessions#report'
  
  # OUTINGS
  resources :outings
  root to: 'application#index'
  
end

app/models/eyepiece.rb
# == Schema Information
#
# Table name: eyepieces
#
#  id           :integer          not null, primary key
#  name         :string
#  focal_length :decimal(, )
#  ocular       :decimal(, )
#  apparent_fov :decimal(, )
#  size         :decimal(, )
#  description  :text
#  notes        :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  brand        :string
#

#
# Classe modello per la tabella "eyepieces".
#
class Eyepiece < ApplicationRecord
  # verifica la correttezza dei dati inseriti per i campi specificati.
  validates :name, :brand, :focal_length, :ocular, :apparent_fov, :size, presence: true

  before_save :trim_data

  # relazioni
  #has_many :observations, dependent: :destroy
  
  private

  # Funzione che arrotonda i valori dei campi "focal_length" e "apparent_fov"
  # a tre cifre decimali.
  def trim_data
    self.focal_length = self.focal_length.round(3)
    self.apparent_fov = self.apparent_fov.round(3)
  end

end

app/controllers/eyepieces_controller.rb
#
# Classe controller che implementa le funzionalità CRUD per la classe model "Eyepiece".
#
class EyepiecesController < ApplicationController
  before_action :set_eyepiece, only: [:show, :edit, :update, :destroy]

  # Metodo che recupera gli oculari (eventualmente mediante ricerca), 
  # li ordina, attua una paginazione degli stessi ed in seguito
  # li visualizza.
  def index
  if params[:order] == nil
    params[:order] = 'created_at DESC'
	end
    @q = Eyepiece.ransack(params[:q])
    @eyepieces = @q.result.order(params[:order]).paginate(page: params[:page]) if params[:q].present?
    @eyepieces = Eyepiece.order(params[:order]).paginate(page: params[:page]) unless params[:q].present?
    @eyepiece = Eyepiece.new
  end

  # Metodo ereditato dalla classe ApplicationController.
  def show
  end

  # Metodo che crea un'istanza di Eyepiece, la quale verrà 
  # passata alla vista corrispondente all'URL "/eyepieces/1/edit".
  def new
    @eyepiece = Eyepiece.new
  end

  # Metodo ereditato dalla classe ApplicationController.
  def edit
  end

  # Questo metodo crea un'istanza di Eyepiece e la salva nel database.
  # Se l'operazione si conclude con successo, avverrà una redirezione alla pagina
  # che presenta i dettagli dello strumento creato. In caso contrario, verrà
  # visualizzato un messaggio d'errore.
  def create
    @eyepiece = Eyepiece.new(eyepiece_params)

    respond_to do |format|
      if @eyepiece.save
        format.html { redirect_to @eyepiece, notice: 'Eyepiece was successfully created.' }
        format.json { render :show, status: :created, location: @eyepiece }
      else
        format.html { render :new }
        format.json { render json: @eyepiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che aggiorna un'istanza di Eyepiece. Se l'operazione avviene con successo,
  # avverrà una redirezione alla pagina che visualizza i dettagli dello strumento aggiornato.
  # In caso contrario, verrà visualizzato un messaggio d'errore.
  def update
    respond_to do |format|
      if @eyepiece.update(eyepiece_params)
        format.html { redirect_to @eyepiece, notice: 'Eyepiece was successfully updated.' }
        format.json { render :show, status: :ok, location: @eyepiece }
      else
        format.html { render :edit }
        format.json { render json: @eyepiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che elimina un'istanza di Eyepiece. Se l'operazione avviene con
  # successo, il browser verrà redirezionato alla lista di oculari.
  def destroy
    @eyepiece.destroy
    respond_to do |format|
      format.html { redirect_to eyepieces_url, notice: 'Eyepiece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_eyepiece
      @eyepiece = Eyepiece.find(params[:id])
    end

    # Metodo che imposta i parametri richiesti e ammessi durante la creazione o la modifica
    # di un'istanza di Eyepiece.
    def eyepiece_params
      params.require(:eyepiece).permit(:name, :brand, :focal_length, :ocular, :apparent_fov, :size, :description, :notes)
    end
end

app/helpers/eyepieces_helper.rb
module EyepiecesHelper
end

app/views/eyepieces/_form.html.erb
<%= bootstrap_form_for(@eyepiece) do |f| %>
  <%= f.text_field :name, label: 'Nome:'%>
  <%= f.text_field :brand, label: 'Brand:' %>
  <%= f.text_area :description, label: 'Descrizione:' %>
  <%= f.text_field :focal_length, label: 'Lunghezza focale:' %>
  <%= f.text_field :ocular, label: 'Oculare:' %>
  <%= f.text_field :apparent_fov, label: 'Campo di visione apparente:' %>
  <%= f.text_field :size, label: 'Dimensione:' %>
  <%= f.text_area :notes, label: 'Note:' %>
  <%= f.submit 'Aggiorna' %>
<% end %>

app/views/eyepieces/_new_modal.html.erb
<div class="modal fade" id="new-filter-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Inserimento nuovo oculare</h4>
      </div>
      <div class="modal-body">
        <p>Inserire le informazioni richieste per il nuovo oculare:</p>
        <%= render 'eyepieces/form' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/eyepieces/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Modifica oculare</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', eyepiece: @eyepiece %>
  </div>
</div>
<%= render 'layouts/footer_logged'%>

app/views/eyepieces/index.html.erb
<% if current_user != 'admin' && Date.today > current_user.subscription_expiration+31.days %>
<div class="month_expired">
	<p>La tua sottoscrizione è scaduta da più di un mese non puoi più accedere a queste informazioni</p>
</div>
<% else %>

<%= render 'eyepieces/new_modal' %>
<div class="panel panel-default">
  <div class="panel-heading">
	<% if current_user.role == 'admin' %>
    <h1 class="panel-title">Gestione Oculari</h1>
	<% else %>
	<h1 class="panel-title">Oculari</h1>
	<% end %>
  </div>
  <div class="panel-body">
    <p>Lista oculari magazzino</p>
	<% if current_user.role == 'admin' %>
    <p>
      Azioni disponibili:
      <span>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new-filter-modal">Inserisci nuovo oculare</button>
      </span>
    </p>
	<% end %>
    <hr>
	<%= search_form_for @q, { id: '' } do |f| %>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label :name_cont, 'Cerca per nome' %>
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label :brand_cont, 'Cerca per brand' %>
            <%= f.search_field :brand_cont, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-4 col-sm-offset-4">
          <div class="form-group">
            <label for="order">Ordina risultati per</label>
            <%= select_tag 'order', options_for_select([['Nessuno','created_at DESC'], ['Nome', 'name'], ['Lunghezza focale','focal_length'], ['Oculare','ocular'], ['Campo visione apparente','apparent_fov'], ['Dimensione','size']], params[:order] || ''), class: 'form-control', onchange: "$('#eyepiece_search').submit();" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label 'Lunghezza focale' %>
            <%= f.search_field :focal_length_gteq, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label 'Oculare' %>
            <%= f.search_field :ocular_gteq, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label 'Campo visione app.' %>
            <%= f.search_field :apparent_fov_gteq, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label 'Dimensione' %>
            <%= f.search_field :size_gteq, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-1 col-sm-offset-3">
          <div class="form-group">
            <label>&nbsp;</label>
            <%= f.submit 'Filtra', class: 'btn btn-default form-control' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Brand</th>
        <th>Lunghezza focale</th>
        <th>Oculare</th>
        <th>Campo di visione apparente</th>
        <th>Dimensione</th>
        <th colspan="3">Azioni</th>
      </tr>
    </thead>

    <tbody>
      <% @eyepieces.each do |eyepiece| %>
        <tr>
          <td><%= eyepiece.name %></td>
          <td><%= eyepiece.brand %></td>
          <td><%= number_with_delimiter eyepiece.focal_length, separator: ',' %></td>
          <td><%= number_with_delimiter eyepiece.ocular, separator: ',' %></td>
          <td><%= number_with_delimiter eyepiece.apparent_fov, separator: ',' %></td>
          <td><%= number_with_delimiter eyepiece.size, separator: ',' %></td>
          <td><%= link_to 'Mostra', eyepiece %></td>
		  <% if current_user.role == 'admin' %>
          <td><%= link_to 'Modifica', edit_eyepiece_path(eyepiece) %></td>
          <td><%= link_to 'Elimina', eyepiece, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
          <% end %>
		</tr>
      <% end %>
    </tbody>
  </table>
  <span><center><%= will_paginate @eyepieces, previous_label: 'Precedente', next_label: 'Successivo' %></center></span>
</div>

<% end %>
<%= render 'layouts/footer_logged'%>

app/views/eyepieces/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Creazione nuovo oculare</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', eyepiece: @eyepiece %>
  </div>
</div>
<%= render 'layouts/footer_logged'%>

app/views/eyepieces/show.html.erb
<!-- Vista per visualizzare un singolo oculare -->

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">Informazioni oculare</div>
      <div class="panel-body">
        <p><span><strong>Nome:</strong></span> <%= @eyepiece.name %></p>
        <p><span><strong>Brand:</strong></span> <%= @eyepiece.brand %></p>
        <p><span><strong>Lunghezza focale:</strong></span> <%= @eyepiece.focal_length %></p>
        <p><span><strong>Oculare:</strong></span> <%= @eyepiece.ocular %> mm</p>
        <p><span><strong>Campo di visione apparente:</strong></span> <%= @eyepiece.apparent_fov %>°</p>
        <p><span><strong>Dimensione:</strong></span> <%= @eyepiece.size %></p>
        <p><span><strong>Descrizione:</strong></span> <%= @eyepiece.description %></p>
        <p><span><strong>Note:</strong></span> <%= @eyepiece.notes %></p>
        <%= link_to 'Modifica', edit_eyepiece_url(@eyepiece) %> |
        <%= link_to 'Indietro', eyepieces_path %>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer_logged'%>