config/routes.rb
Rails.application.routes.draw do

  # USERS MANAGEMENT
  devise_for :users
  post '/users', to: 'users#create'
  get '/users/expired', to: 'users#list_expired'

  resources :users

  # FILTERS
  resources :filters
  # TELESCOPES
  resources :telescopes
  # EYEPIECES
  resources :eyepieces
  # BINOCULARS
  resources :binoculars
  # CELESTIAL BODIES
  resources :celestial_bodies
  # OBSERVATIVE SESSIONS
  resources :observative_sessions do
  # OBSERVATIONS
  resources :observations
  end
  get '/report', to: 'observative_sessions#report'
  
  # OUTINGS
  resources :outings
  root to: 'application#index'
  
end

app/models/filter.rb
# == Schema Information
#
# Table name: filters
#
#  id          :integer          not null, primary key
#  name        :string
#  brand       :string
#  description :text
#  notes       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

#
# Classe modello per la tabella "filters".
#
class Filter < ApplicationRecord
  # verifica la correttezza dei dati inseriti per i campi specificati.
  validates :name, :description, :brand, presence: true
  
  # relazioni
  #has_many :observations, dependent: :destroy
  
end

app/controllers/filters_controller.rb
#
# Classe controller che implementa le funzionalità CRUD per la classe model "Filter".
#
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # Metodo che recupera i filtri (eventualmente mediante ricerca), 
  # li ordina, attua una paginazione degli stessi ed in seguito
  # li visualizza.
  def index
	if params[:order] == nil
    params[:order] = 'created_at DESC'
	end
    @q = Filter.ransack(params[:q])
    @filters = @q.result.order(params[:order]).paginate(page: params[:page]) if params[:q].present?
    @filters = Filter.order(params[:order]).paginate(page: params[:page]) unless params[:q].present?
    @filter = Filter.new
  end

  # Metodo ereditato dalla classe ApplicationController.
  def show
  end

  # Metodo che crea un'istanza di Filter, la quale verrà 
  # passata alla vista corrispondente all'URL "/filters/1/edit".
  def new
    @filter = Filter.new
  end

  # Metodo ereditato dalla classe ApplicationController.
  def edit
  end

  # Questo metodo crea un'istanza di Filter e la salva nel database.
  # Se l'operazione si conclude con successo, avverrà una redirezione alla pagina
  # che presenta i dettagli dello strumento creato. In caso contrario, verrà
  # visualizzato un messaggio d'errore.
  def create
    @filter = Filter.new(filter_params)

    respond_to do |format|
      if @filter.save
        format.html { redirect_to @filter, notice: 'Filter was successfully created.' }
        format.json { render :show, status: :created, location: @filter }
      else
        format.html { render :new }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che aggiorna un'istanza di Filter. Se l'operazione avviene con successo,
  # avverrà una redirezione alla pagina che visualizza i dettagli dello strumento aggiornato.
  # In caso contrario, verrà visualizzato un messaggio d'errore.
  def update
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to @filter, notice: 'Filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @filter }
      else
        format.html { render :edit }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che elimina un'istanza di Filter. Se l'operazione avviene con
  # successo, il browser verrà redirezionato alla lista di filtri.
  def destroy
    @filter.destroy
    respond_to do |format|
      format.html { redirect_to filters_url, notice: 'Filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Metodo che imposta i parametri richiesti e ammessi durante la creazione o la modifica
    # di un'istanza di Filter.
    def filter_params
      params.require(:filter).permit(:name, :brand, :description, :notes)
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<%= bootstrap_form_for(@filter) do |f| %>
  <%= f.text_field :name, label: 'Nome:' %>
  <%= f.text_field :brand, label: 'Brand:' %>
  <%= f.text_area :description, label: 'Descrizione:' %>
  <%= f.text_area :notes, label: 'Note:' %>
  <%= f.submit 'Aggiorna' %>
<% end %>

app/views/filters/_new_modal.html.erb
<div class="modal fade" id="new-filter-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Inserimento nuovo filtro</h4>
      </div>
      <div class="modal-body">
        <p>Inserire le informazioni richieste per il nuovo filtro:</p>
        <%= render 'filters/form' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/filters/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Modifica filtro</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', filter: @filter %>
  </div>
</div>
<%= render 'layouts/footer_logged'%>

app/views/filters/index.html.erb
<% if current_user != 'admin' && Date.today > current_user.subscription_expiration+31.days %>
<div class="month_expired">
	<p>La tua sottoscrizione è scaduta da più di un mese non puoi più accedere a queste informazioni</p>
</div>
<% else %>

<%= render 'filters/new_modal' %>
<div class="panel panel-default">
  <div class="panel-heading">
	<% if current_user.role == 'admin' %>
    <h1 class="panel-title">Gestione Filtri</h1>
	<% else %>
	<h1 class="panel-title">Filtri</h1>
	<% end %>
  </div>
  <div class="panel-body">
    <p>Lista filtri magazzino</p>
	<% if current_user.role == 'admin' %>
    <p>
      Azioni disponibili:
      <span>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new-filter-modal">Inserisci nuovo filtro</button>
      </span>
    </p>
	<% end %>
    <hr>
	<%= search_form_for @q, { id: '' } do |f| %>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label :name_cont, 'Cerca per nome' %>
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <%= f.label :brand_cont, 'Cerca per brand' %>
            <%= f.search_field :brand_cont, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-4 col-sm-offset-3">
          <div class="form-group">
            <label for="order">Ordina risultati per</label>
            <%= select_tag 'order', options_for_select([['Nessuno','created_at DESC'], ['Nome', 'name'], ['Brand','brand']], params[:order] || ''), class: 'form-control', onchange: "$('#filter_search').submit();" %>
          </div>
        </div>
      <div class="col-sm-1">
        <div class="form-group">
          <label>&nbsp;</label>
          <%= f.submit 'Filtra', class: 'btn btn-default form-control' %>
        </div>
      </div>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Brand</th>
        <th>Descrizione</th>
        <th colspan="3">Azioni</th>
      </tr>
    </thead>

    <tbody>
      <% @filters.each do |filter| %>
        <tr>
          <td><%= filter.name %></td>
          <td><%= filter.brand %></td>
          <td><%= filter.description %></td>
          <td><%= link_to 'Mostra', filter %></td>
		  <% if current_user.role == 'admin' %>
          <td><%= link_to 'Modifica', edit_filter_path(filter) %></td>
          <td><%= link_to 'Elimina', filter, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
          <% end %>
		</tr>
      <% end %>
    </tbody>
  </table>
  <span><center><%= will_paginate @filters, previous_label: 'Precedente', next_label: 'Successivo' %></center></span>
</div>

<% end %>
<%= render 'layouts/footer_logged'%>

app/views/filters/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Creazione nuovo filtro</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', filter: @filter %>
  </div>
</div>
<%= render 'layouts/footer_logged'%>

app/views/filters/show.html.erb
<!-- Vista per visualizzare un singolo filtro -->

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">Informazioni filtro</div>
      <div class="panel-body">
        <p><span><strong>Nome:</strong></span> <%= @filter.name %></p>
        <p><span><strong>Brand:</strong></span> <%= @filter.brand %></p>
        <p><span><strong>Descrizione:</strong></span> <%= @filter.description %></p>
        <p><span><strong>Note:</strong></span> <%= @filter.notes %></p>
        <%= link_to 'Modifica', edit_filter_url(@filter) %> |
        <%= link_to 'Indietro', filters_path %>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer_logged'%>