config/routes.rb
Rails.application.routes.draw do

  # USERS MANAGEMENT
  devise_for :users
  post '/users', to: 'users#create'
  get '/users/expired', to: 'users#list_expired'

  resources :users

  # FILTERS
  resources :filters
  # TELESCOPES
  resources :telescopes
  # EYEPIECES
  resources :eyepieces
  # BINOCULARS
  resources :binoculars
  # CELESTIAL BODIES
  resources :celestial_bodies
  # OBSERVATIVE SESSIONS
  resources :observative_sessions do
  # OBSERVATIONS
  resources :observations
  end
  get '/report', to: 'observative_sessions#report'
  
  # OUTINGS
  resources :outings
  root to: 'application#index'
  
end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "STELLAR1", root_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Utenti <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Tutti", users_path %></li>
                  <li><%= link_to "Tessere scadute", users_expired_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Strumenti <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Binocoli", binoculars_path %></li> 
				  <li><%= link_to "Telescopi", telescopes_path %></li>
                  <li><%= link_to "Oculari", eyepieces_path %></li>
                  <li><%= link_to "Filtri", filters_path %></li>
                </ul>
              </li>
              <li>
                <%= link_to "Corpi Celesti", celestial_bodies_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <p>Benvenuto <%= current_user.name %><br />
				<% if Date.today.between?(current_user.subscription_expiration-15, current_user.subscription_expiration) %>
				<span class="expiring">
				La tua tessera scade il <%= current_user.subscription_expiration.strftime("%d/%m/%Y") %>
				</span>
				<% elsif Date.today > current_user.subscription_expiration %>
				<span class="expiring">
				<strong>La tua tessera è scaduta il <%= current_user.subscription_expiration.strftime("%d/%m/%Y") %></strong>
				</span>
				<% else %>
				La tua tessera scade il <%= current_user.subscription_expiration.strftime("%d/%m/%Y") %>
				<% end %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
<% if Date.today > current_user.subscription_expiration %>
<div class="subscription_expired">
<p>La tua tessera è scaduta ti preghiamo di rinnovarla.</p>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<div class="row footer">
		<div class="col-sm-6">
		<h1>Sede</h1>
		<p>Osservatorio s.r.l.<br />
		Sede legale: via X 1, Udine<br />
		Partita Iva: 12345678900123345770998765 <br />
		iscritta presso il Registro AAA al n. <br />
		in persona del legale rappresentante pro tempore, <br />
		Sig. Luca Verdi </p>
		</div>
		<div class="col-sm-6">
		<h1>Contatti</h1>
		<p>Luca Verdi<br />
		e-mail:<a href="mailto:luca.verdi@mail.com"> luca.verdi@mail.com</a></p>
		<p>Sito sviluppato da <a href="">Alpha1</a></p>
		</div>
	</div>
</footer>

app/views/layouts/_footer_logged.html.erb
<footer>
	<div class="row footer">
		<div class="col-sm-6">
		<h1>Sede</h1>
		<p>Osservatorio s.r.l.<br />
		Sede legale: via X 1, Udine<br />
		Partita Iva: 12345678900123345770998765 <br />
		iscritta presso il Registro AAA al n. <br />
		in persona del legale rappresentante pro tempore, <br />
		Sig. Luca Verdi </p>
		</div>
		<div class="col-sm-6">
		<h1>Contatti</h1>
		<p>Luca Verdi<br />
		e-mail:<a href="mailto:luca.verdi@mail.com"> luca.verdi@mail.com</a></p>
		<p><a href="">Mappa del sito</a></p>
		<p>Sito sviluppato da <a href="">Alpha1</a></p>
		</div>
	</div>
</footer>

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "STELLAR1", root_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Strumenti <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Binocoli", binoculars_path %></li>
				  <li><%= link_to "Telescopi", telescopes_path %></li>
                  <li><%= link_to "Oculari", eyepieces_path %></li>
                  <li><%= link_to "Filtri", filters_path %></li>
                </ul>
              </li>
			  <li>
                <%= link_to "Corpi Celesti", celestial_bodies_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
				<p>Benvenuto <%= current_user.name %><br />
				<% if Date.today.between?(current_user.subscription_expiration-15, current_user.subscription_expiration) %>
				<span class="expiring">
				La tua tessera scade il <%= current_user.subscription_expiration.strftime("%d/%m/%Y") %>
				</span>
				<% elsif Date.today > current_user.subscription_expiration %>
				<span class="expiring">
				<strong>La tua tessera è scaduta il <%= current_user.subscription_expiration.strftime("%d/%m/%Y") %></strong>
				</span>
				<% else %>
				La tua tessera scade il <%= current_user.subscription_expiration.strftime("%d/%m/%Y") %>
				<% end %>
				</p>
			  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
<% if Date.today.between?(current_user.subscription_expiration+30, current_user.subscription_expiration) %>
<div class="subscription_expired">
<p>La tua tessera è scaduta ti preghiamo di rinnovarla entro 1 mese.</p>
</div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar1</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/admin_navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar1</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar1</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
		<%= render 'layouts/user_navbar' %>
      <%= yield %>
    </div>
  </body>
</html>